name: CI - Image & Dockerfile Security Scan
permissions:
  contents: read
  security-events: write
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  image-and-dockerfile-scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [api, worker]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./${{ matrix.service }}
        push: false
        tags: todo-${{ matrix.service }}:latest
        load: true

    - name: Run Trivy image vulnerability scanner (SARIF)
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: todo-${{ matrix.service }}:latest
        format: 'sarif'
        output: 'trivy-image-results-${{ matrix.service }}.sarif'

    - name: Upload Trivy image scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-image-results-${{ matrix.service }}.sarif'

    - name: Run Trivy image scan (table format)
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: todo-${{ matrix.service }}:latest
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'

    - name: Run Trivy config scan on Dockerfile
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: config
        format: table
        exit-code: '1'
        severity: 'CRITICAL,HIGH'
        ignore-unfixed: true
        input: ./${{ matrix.service }}/Dockerfile
